server:
  port: 6066

spring:
  application:
    name: years-service

  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:/research/dataset/database.sqlite
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest